### ISSUE TITLE
Logo Theme Settings: No Widget Overlay should be under a different header

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#117]
As the header text isn't visible when widgets are added it makes little sense to have this setting listed under the same heading.

**Comment by Misplon** [comment]
Hey, @AlexGStapleton. To confirm we're on the same page; No Widget Overlay stops the header widgets from overlapping onto the logo if too many are added. It drops the header widget area down onto a new row below the logo if it's detected that a logo overlap will occur. It's because it stops an overlap onto the logo and drops widgets onto a new line that it's in this section.

**Comment by AlexGStapleton** [comment]
I'm aware. My issue is not with the functionality, it's the location of the setting in the customizer.

**Comment by Misplon** [comment]
Each setting is prefixed with the section name so I don't know that we
could move a setting. Assuming we could, what section are you proposing we
move it to?

**Comment by gregpriday** [comment]
Aaah, yeah, it's a bit of a limitation in the settings framework that the key of the setting is tied to the section. It's possible to move them using some migration code, but this opens us up to some potential issues. So it's better for us to avoid this if possible.

**Comment by AlexGStapleton** [comment]
If that's the case - lets just leave it.
