### ISSUE TITLE
UX Customizer issue: Scroll to Top and Sticky Mobile Menu work when Mobile Navigation is enabled

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#119]
The Mobile Navigation navigation setting doesn't seem to matter in the customizer. Only the individual settings do which isn't how it is outside of the customizer. This can lead to confusion as to why the sticky menu is working in the customizer and not on the frontend.

**Comment by adiraomj** [comment]
@AlexGStapleton did you test this issue out on a mobile device.

The **Mobile Navigation** setting makes use of [`wp_is_mobile`](https://codex.wordpress.org/Function_Reference/wp_is_mobile).

**Comment by AlexGStapleton** [comment]
It does? I've never had an issue with using that setting when not on a mobile device or when using the Chrome device emulation. :confused: 

Regardless, no - I didn't see the need due it being unlikely the user would be adjusting customizer settings on a mobile device. The mobile navigation shouldn't be dependent on wp_is_mobile in the customizer as in its current state it will confuse people as to why that setting doesn't do what it says it does when using the customizer.

**Comment by adiraomj** [comment]
Unless this is an issue, I don't think we should touch this. Moreover the setting description does mention that this is only for mobile devices.  What do you think @gregpriday ?

**Comment by Misplon** [comment]
@AlexGStapleton I understand your points. This setting was introduced to allow users to active the sticky menu and back to top for mobile users. By default, those elements don't work on mobile. This setting enables the sticky menu and back to top on mobile.

We can update the label and description but otherwise can't change the setting for legacy reasons. Also, without this setting users can't enable sticky menu and back to top for mobile users. This was a big request before we introduced this setting.

**Comment by Misplon** [comment]
@AlexGStapleton Going to work this here for a little clarity: https://github.com/siteorigin/vantage/issues/131. Thanks :)
