### ISSUE TITLE
UX Add Link Underline on Hover: Is only applied to post contents and text widgets

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#125]
I really like the idea of this setting but it's odd that it's listed under the general settings group and only affects the post contents and text widgets area. It should affect either everything, be moved somewhere less general or be relabeled to include content like the content link colors.

**Comment by Misplon** [comment]
@AlexGStapleton We had a relatively in-depth discussion about this when the setting was added. We aren't able to move sections due to limitations in the framework. The scope of the underline was decided on due to legacy styles. One of those situations where we had to add what we could while still respecting the styling existing users had.

**Comment by Misplon** [comment]
https://github.com/siteorigin/vantage/issues/65
