### ISSUE TITLE
Customizer: Duplicate Menu on adjustment

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#240]
If you make adjustments to menu, the menu will be duplicated. This happens at all menu levels.

Reference GIF:
![](https://i.imgur.com/H13Hel6.gif)

I've checked our other themes and this issue doesn't occur.

**Comment by Misplon** [comment]
@adiraomj Could you perhaps take a look for us?

**Comment by Remzi1993** [comment]
@Misplon Is this fixed?

**Comment by AlexGStapleton** [comment]
Hi @Remzi1993,

Unfortunately, this issue is still affecting the customizer. Please note that this issue doesn't affect the menu outside of the customizer.

**Comment by Remzi1993** [comment]
That's very unfortunate @AlexGStapleton

**Comment by gregpriday** [comment]
I've recreated this on my side. Taking a look now.

**Comment by Remzi1993** [comment]
@gregpriday Thank you very much!

**Comment by gregpriday** [comment]
I've managed to track down the cause of this. It came about because of a change to how the Customizer dynamically replaces a navigation menu (without doing a full page refresh). The method it's using isn't compatible with how Vantage's mobile navigation works.

It seems like the Customizer is deleting the last instance of the menu it sees in the DOM, which in the case of Vantage is the hidden mobile nav. After this it readds the navigation, which is why we're seeing additional copies being added.

The easiest solution here would be to disable mobile navigation completely when in the customizer.

The other option would be to find if there's a Customizer update event of sorts that we can hook into and clean things up. There might also be a way to tell the Customizer to do a full page refresh rather than using the partial change method. This is possible for settings in the customizer.

I'll investigate tomorrow.
