### ISSUE TITLE
Loop templates: If media post type is selected, display media in place of typical featured image

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/vantage#4]
When the user builds a post loop query with the SiteOrigin Post Builder post loop widget (with bundle installed) with the post type set to media, and post_status=any set certain templates won't display the media correctly.

Carousel Slider
![Carousel Slider](https://i.imgur.com/96IXsC9.png)

Grid
![Grid](https://i.imgur.com/GxXXfW4.png)

Slider shows absolutely nothing - not even the image name.

**Comment by adiraomj** [comment]
@AlexGStapleton as far I can see, the images you have added above seem to be doing what they have been designed to do.

For the carousel: what you are seeing is a situation wherein the post does not have a set featured image and only the space assigned to it is being shown. My guess is that since the widget is a carousel, users would be expected to set the post query for posts that do have a featured image.

For the grid: again as above, the posts do not have a featured image. So only the post title and excerpt is being displayed.

It would be a little helpful, if you could expand on what is expected of the widget. Thanks :)

**Comment by AlexGStapleton** [comment]
The issue here is though that as I've set the post type to media it's not possible to set a featured image. The image is quite literally the "post" itself. I'm going to rename the post title so it's slightly more clear what the issue is.

**Comment by adiraomj** [comment]
Ohhh.. Will check it out now. :) Thanks.
